import type { ActionDefinition } from "../../core/types.ts";

import { s } from "../../core/json-schema.ts";
import { defineProviderAction } from "../../core/provider-definition.ts";

const issuedBadge = s.looseObject("An issued badge with recipient details and verification URLs.", {
  issue_id: s.string("Encrypted issue ID."),
  recipient_name: s.string("Recipient's full name."),
  recipient_email: s.string("Recipient's email address."),
  recipient_phone: s.string("Recipient's phone number."),
  badge_id: s.string("Encrypted badge ID."),
  badge_name: s.string("Badge name."),
  organization_name: s.string("Issuing organization name."),
  issue_date: s.string("Badge issue date."),
  expire_date: s.nullable(s.string("Badge expiration date, if set.")),
  serial_number: s.nullable(s.string("Badge serial number, if set.")),
  memo: s.nullable(s.string("Additional notes, if set.")),
  public_url: s.string("Public verification URL."),
  pdf_url: s.string("PDF download URL."),
  metadata: s.nullable(s.looseObject("Custom field values and additional metadata.", {})),
  created_at: s.string("Record creation timestamp."),
  updated_at: s.string("Record last update timestamp."),
});

export const issueBadgeActions: ActionDefinition[] = [
  defineProviderAction("issue_badge", {
    name: "list_badges",
    description:
      "List up to 100 badge templates in your IssueBadge organization. The API does not expose pagination for this list.",
    operationType: "read",
    requiredScopes: [],
    inputSchema: s.requiredObject("Input for listing badge templates.", {}),
    outputSchema: s.looseObject("Badge template list response.", {
      success: s.boolean("Whether the request succeeded."),
      message: s.string("Response message."),
      data: s.array(
        "Available badge templates.",
        s.looseObject("A badge template.", {
          id: s.string("Encrypted badge ID."),
          name: s.string("Badge name."),
        }),
      ),
    }),
  }),
  defineProviderAction("issue_badge", {
    name: "issue_badge",
    description:
      "Issue an existing IssueBadge template to a recipient and create a public verification URL. Providing an email address triggers a notification email. Reuse an idempotency key to retrieve the existing issuance without issuing it again.",
    operationType: "write",
    requiredScopes: [],
    inputSchema: s.requiredObject("Input for issuing a badge.", {
      badge_id: s.nonEmptyString("Encrypted badge ID from list_badges."),
      name: s.nonEmptyString("Recipient's full name.", { maxLength: 200 }),
      email: s.optional(s.email("Recipient's email address for notification.")),
      phone: s.optional(s.string("Recipient's phone number.")),
      idempotency_key: s.optional(
        s.nonEmptyString("Unique key to prevent duplicate issuance. Generated by IssueBadge when omitted.", {
          maxLength: 100,
        }),
      ),
      metadata: s.optional(s.looseObject("Custom field values and additional metadata.", {})),
    }),
    outputSchema: s.looseObject("Badge issuance response, including an existing issue on an idempotency replay.", {
      success: s.boolean("Whether the request succeeded."),
      IssueId: s.string("Encrypted issue ID for tracking."),
      publicUrl: s.string("Public verification URL."),
    }),
  }),
  defineProviderAction("issue_badge", {
    name: "list_issued_badges",
    description:
      "List issued IssueBadge records with pagination and optional badge, recipient name, and recipient email filters.",
    operationType: "read",
    requiredScopes: [],
    inputSchema: s.requiredObject("Input for listing issued badges.", {
      badge_id: s.optional(s.nonEmptyString("Filter by encrypted badge ID.")),
      recipient_name: s.optional(s.string("Search by recipient name using a partial match.")),
      recipient_email: s.optional(s.string("Search by recipient email using a partial match.")),
      page: s.optional(s.integer("Page number, starting at 1. Defaults to 1.", { minimum: 1 })),
      per_page: s.optional(s.integer("Items per page, up to 100. Defaults to 10.", { minimum: 1, maximum: 100 })),
    }),
    outputSchema: s.looseObject("Paginated issued badge response.", {
      success: s.boolean("Whether the request succeeded."),
      data: s.array("Issued badges matching the filters.", issuedBadge),
      pagination: s.looseObject("Pagination metadata.", {
        current_page: s.integer("Current page number."),
        per_page: s.integer("Items per page."),
        total: s.integer("Total number of matching records."),
        total_pages: s.integer("Total number of pages."),
        has_more: s.boolean("Whether another page is available."),
      }),
    }),
  }),
  defineProviderAction("issue_badge", {
    name: "get_issued_badge",
    description:
      "Retrieve an issued IssueBadge record by encrypted issue ID, including recipient details, metadata, verification URL, and PDF URL.",
    operationType: "read",
    requiredScopes: [],
    inputSchema: s.requiredObject("Input for retrieving an issued badge.", {
      id: s.nonEmptyString("Encrypted issue ID."),
    }),
    outputSchema: s.looseObject("Issued badge details response.", {
      success: s.boolean("Whether the request succeeded."),
      data: issuedBadge,
    }),
  }),
];
